server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    bufferDurationMs: 400
    youtubePlaylistLoadLimit: 6
    playerUpdateInterval: 5
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true

logging:
  file: ./logs/
  level:
    root: INFO
    lavalink: INFO
    lavalink.player: INFO
    lavalink.rest: INFO
    lavalink.ws: INFO

metrics:
  prometheus:
    enabled: false
